
  - id: doi:10.1021/acs.nanolett.3c04118
  type: journal
  image: images/paper_pic/hBN_NanoLett.png

- id: doi:10.1364/OPTICA.499059
  type: journal
  image: images/paper_pic/Optica.png

- id: doi:10.1021/acs.nanolett.2c01819
  type: journal
  image: images/paper_pic/slot_NanoLett.png

- id: doi:10.1038/s41565-021-01023-x
  type: journal
  image: images/paper_pic/Superlattice_NatureNano.png

- id: doi:10.1021/acsphotonics.0c01964
  type: journal
  image: images/paper_pic/All_ACS.png

- id: doi:10.1109/LED.2020.3042310
  type: journal
  image: images/paper_pic/IEEE.png

- id: doi:10.1002/adfm.202003601
  type: journal
  image: images/paper_pic/gelatin_AFM.png

- id: doi:10.1002/adfm.201906016
  type: journal
  image: images/paper_pic/PEDOT_AFM.png

- id: doi:10.1002/adma.201904752
  type: journal
  image: images/paper_pic/PEDOT_AM.png

- id: doi:10.1016/j.mtla.2019.100425
  type: journal
  image: images/paper_pic/molten_TiC.png

- id: doi:10.1016/j.mtbio.2019.100024
  type: journal
  image: images/paper_pic/3Dprinting.png

- id: doi:10.1016/j.promfg.2017.07.066
  type: journal
  image: images/paper_pic/TiC_molten.png
  
