# Thumbnail/pdf additions

  - id: doi.org/10.1021/acs.nanolett.3c04118
    image: 
      images/paper_pic/hBN_NanoLett.png

 - id: doi.org/10.1364/OPTICA.499059
    image: 
      images/paper_pic/Optica.png

  - id: doi.org/10.1021/acs.nanolett.2c01819
    image: 
      images/paper_pic/slot_NanoLett.png

  - id: doi.org/10.1038/s41565-021-01023-x
    image: 
      images/paper_pic/Superlattice_NatureNano.png

  - id: doi.org/10.1021/acsphotonics.0c01964
    image: 
      images/paper_pic/All_ACS.png

  - id: 10.1109/LED.2020.3042310
    image: 
      images/paper_pic/IEEE.png

  - id:  doi.org/10.1002/adfm.202003601
    image: 
      images/paper_pic/gelatin_AFM.png

   - id:  doi.org/10.1002/adfm.201906016
    image: 
      images/paper_pic/PEDOT_AFM.png

    - id:  doi.org/10.1002/adma.201904752
    image: 
      images/paper_pic/PEDOT_AM.png

    - id:  doi.org/10.1016/j.mtla.2019.100425
    image: 
      images/paper_pic/molten_TiC.png

    - id:  doi.org/10.1016/j.mtbio.2019.100024
    image: 
      images/paper_pic/3Dprinting.png

    - id:  doi.org/10.1016/j.promfg.2017.07.066
    image: 
      images/paper_pic/TiC)molten.png

  
